apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: helloweb-svc
spec:
  ports:
    - name: 85-8080
      port: 85
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello
    tier: web
  type: ClusterIP
